version: "3.9"

services:
  backend:
    build: ./backend
    container_name: rag-backend
    volumes:
      - ./backend/data:/app/data   # persist docs + index
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434  # backend will call Ollama
    depends_on:
      - ollama

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama_data:
